# ************************************************************
# Sequel Pro SQL dump
# Версия 4499
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Адрес: localhost (MySQL 5.5.42)
# Схема: mls
# Время создания: 2016-02-09 12:59:17 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Дамп таблицы articles
# ------------------------------------------------------------

DROP TABLE IF EXISTS `articles`;

CREATE TABLE `articles` (
  `article_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(256) NOT NULL DEFAULT '',
  `body` text NOT NULL,
  `text_preview` varchar(128) NOT NULL DEFAULT '',
  `category` int(11) NOT NULL,
  `date` date DEFAULT NULL,
  `preview` varchar(256) DEFAULT NULL,
  `language` varchar(11) NOT NULL DEFAULT '',
  PRIMARY KEY (`article_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `articles` WRITE;
/*!40000 ALTER TABLE `articles` DISABLE KEYS */;

INSERT INTO `articles` (`article_id`, `title`, `body`, `text_preview`, `category`, `date`, `preview`, `language`)
VALUES
	(1,'TEST_1','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?\n','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',1,'2015-12-25','one_new_fish.png','en'),
	(2,'Test_2','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',2,'2015-12-23','one_new_fish.png','ru'),
	(3,'test_3','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-22','one_new_fish.png','ua'),
	(4,'test_4','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias. Harum rem molestias.',4,'2015-12-21','one_new_fish.png','ua'),
	(5,'test_5','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-20','one_new_fish.png','ua'),
	(6,'test_6','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',4,'2015-12-19','one_new_fish.png','en'),
	(7,'test_7','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-18','one_new_fish.png','ru'),
	(8,'test_8','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',4,'2015-12-17','one_new_fish.png','ru'),
	(9,'test_9','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-26','one_new_fish.png','en'),
	(10,'test_10','Lorem ipsum dolor sit amet, consectetur adipisicing elit.<br> Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?\n<ul>\n	<li> first </li>\n	<li> second </li>\n</ul>','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias',3,'2015-12-27','one_new_fish.png','ua'),
	(11,'test_11','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-28','one_new_fish.png','en'),
	(12,'Какая-то статья','<h3>This is a demo of Trumbowyg</h3> <p> A simple paragraph, <strong>strong</strong> and <em>emphasis</em> funny test. </p> <p style=\"text-align: center;\"> <img src=\"https://www.thefwa.com/library/yy-03-6F1C.jpg\" alt=\"A beautiful website by Ultranoir\"> </p> <blockquote> “Trumbowyg is awesome!” — Alex-D </blockquote><blockquote><br></blockquote> <iframe src=\"//www.slideshare.net/slideshow/embed_code/key/rGNAtAAYCUqSpA\" width=\"595\" height=\"485\" frameborder=\"0\" marginwidth=\"0\" marginheight=\"0\" scrolling=\"no\" style=\"border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;\" allowfullscreen=\"\"> </iframe> <p style=\"margin-bottom:5px\"> <strong> <a href=\"//www.slideshare.net/CBInsights/2016-tech-ipo-report\" title=\"2016 Tech IPO Report\" target=\"_blank\">2016 Tech IPO Report</a> </strong> from <strong><a href=\"//www.slideshare.net/CBInsights\" target=\"_blank\">CB Insights</a></strong> </p><br><br>','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias. Harum rem molestias.',4,'2015-12-28','one_new_fish.png','en'),
	(13,'test_300','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-22','one_new_fish.png','ua'),
	(14,'test_30','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-22','one_new_fish.png','ua'),
	(15,'test_20','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-22','one_new_fish.png','ua'),
	(16,'test_40','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-22','one_new_fish.png','ua'),
	(17,'test_50','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-22','one_new_fish.png','ua'),
	(18,'test_500','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias, sed eveniet veniam maxime voluptates mollitia nulla dignissimos quos expedita autem dolorum culpa fugiat perspiciatis! Molestiae doloribus optio cum quasi repellendus iusto asperiores placeat blanditiis beatae architecto! Unde veritatis ipsa consequatur, voluptate doloremque tenetur quis minima? Ipsam neque, repellat modi nisi asperiores itaque laudantium, quasi eveniet tempora aliquam magni iusto a vel nostrum ut unde officiis facilis saepe voluptatum perferendis voluptatem harum sapiente molestias! Eligendi odio, quos tenetur error hic dolorem praesentium doloremque itaque rem! Repellat ipsa, ut sequi optio porro hic voluptates recusandae quasi libero temporibus, voluptatum. Aliquam voluptas itaque beatae dicta debitis consequatur ex nisi est, doloremque distinctio quas nihil? Eius libero, commodi numquam quas magni ipsa, ipsum repellat fugit soluta nihil distinctio, labore aliquam tempore. Neque cum ratione harum est, commodi velit numquam aspernatur ut in assumenda sapiente eius vitae reiciendis soluta mollitia quibusdam a inventore perferendis libero hic laboriosam ipsa, possimus optio tempore! Reprehenderit corporis quibusdam vero, eum delectus voluptatibus dicta, alias quos esse nulla aspernatur! Non fuga corrupti perspiciatis aperiam fugit porro labore? Ut et pariatur dolore recusandae est voluptatum suscipit placeat nulla eos, omnis tempore veniam velit officia sed, ex error ducimus totam! Quam quia est harum porro ipsam et repudiandae quod quidem vero reiciendis exercitationem, id enim eaque minus beatae accusamus ipsa ratione illo aut ullam inventore. Accusamus officiis reiciendis animi rerum, vero ipsa atque adipisci quisquam, qui officia sed, ea perspiciatis eveniet et! Expedita qui eveniet beatae velit, porro et nobis?','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum rem molestias.',3,'2015-12-22','one_new_fish.png','ua');

/*!40000 ALTER TABLE `articles` ENABLE KEYS */;
UNLOCK TABLES;


# Дамп таблицы counters
# ------------------------------------------------------------

DROP TABLE IF EXISTS `counters`;

CREATE TABLE `counters` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(256) NOT NULL DEFAULT '',
  `title_ru` varchar(256) NOT NULL,
  `title_en` varchar(256) NOT NULL,
  `date` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `counters` WRITE;
/*!40000 ALTER TABLE `counters` DISABLE KEYS */;

INSERT INTO `counters` (`id`, `title`, `title_ru`, `title_en`, `date`)
VALUES
	(1,'Дослидження 1','Исследование 1','Research 1','2016-02-12 12:40:00');

/*!40000 ALTER TABLE `counters` ENABLE KEYS */;
UNLOCK TABLES;


# Дамп таблицы feedback
# ------------------------------------------------------------

DROP TABLE IF EXISTS `feedback`;

CREATE TABLE `feedback` (
  `feedback_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(256) NOT NULL DEFAULT '',
  `email` varchar(256) NOT NULL DEFAULT '',
  `message` text NOT NULL,
  `subscribe` int(11) DEFAULT NULL,
  PRIMARY KEY (`feedback_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `feedback` WRITE;
/*!40000 ALTER TABLE `feedback` DISABLE KEYS */;

INSERT INTO `feedback` (`feedback_id`, `name`, `email`, `message`, `subscribe`)
VALUES
	(1,'Vasya','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',1),
	(2,'PETYA','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',0),
	(3,'IVAN','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',0),
	(4,'gosha_k','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',0),
	(5,'petya','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',0),
	(6,'debil','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',1),
	(7,'dan','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',0),
	(8,'zopa_s_ruchkami','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',0),
	(9,'fuck','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',1),
	(10,'you','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',1),
	(11,'bitch','vasya@vsya.com','Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam repellat repudiandae maiores quos commodi tempore dolore ab earum expedita quisquam.',1);

/*!40000 ALTER TABLE `feedback` ENABLE KEYS */;
UNLOCK TABLES;


# Дамп таблицы migrations
# ------------------------------------------------------------

DROP TABLE IF EXISTS `migrations`;

CREATE TABLE `migrations` (
  `migration` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

LOCK TABLES `migrations` WRITE;
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;

INSERT INTO `migrations` (`migration`, `batch`)
VALUES
	('2014_10_12_000000_create_users_table',1),
	('2014_10_12_100000_create_password_resets_table',1);

/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;
UNLOCK TABLES;


# Дамп таблицы password_resets
# ------------------------------------------------------------

DROP TABLE IF EXISTS `password_resets`;

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `password_resets_email_index` (`email`),
  KEY `password_resets_token_index` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



# Дамп таблицы users
# ------------------------------------------------------------

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;

INSERT INTO `users` (`id`, `name`, `email`, `password`, `remember_token`, `created_at`, `updated_at`)
VALUES
	(1,'Darth_Vader','darthv@deathstar.com','$2y$10$1GmwdLbXKy4ooicaWA6KV.ah60ZxmsCkVFqVPLN8C6V1khwnJumAO','ASAS5SD9BWK0juzmaP44jvjPiZPApGE5nnxl2G1YNVJ0rYOvy9uA0g9uEoMN','2015-12-27 14:49:18','2015-12-27 14:49:18'),
	(2,'goodsidesoldier','lightwalker@rebels.com','$2y$10$liUC/sVGzxXpL7I7iUZb7OGJo00pedcFHDnOw.AjutTBUD/nlFq1i',NULL,'2015-12-25 09:24:33','2015-12-25 09:24:33'),
	(3,'greendemon','dancingsmallman@rebels.com','$2y$10$gA9hQjOhauNjHa1JJjVW4ej9MdZz7Dy8T3oC7cfN97HqoK3urVbUa','9S1SEE4QjFTsFmwePUTNo35RUM2E0IK3LaW5tocNor4EenJyOV17n73IY3mr','2015-12-25 09:38:53','2015-12-25 09:38:53');

/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
